### PR TITLE
Add Articles: Patching Code, MonoMod Examples & MonoMod Docs

### PR DESCRIPTION
**Pull request by Hamunii**
Adds article **Patching Code** with the article **MonoMod Examples** and **MonoMod Docs** under it, under the **Fundamentals** section, with various examples for Hooks and ILHooks.

~~Currently a work in progress.~~ Ready!

### CODE REVIEW

**Comment by Hamunii** [comment]
Okay I added the `IEnumerator` stuff already (although very lazily just so it would be there already) and I also wrote a bit of documentation based off of the official documentation, with the most significant parts to help modders find that stuff.

**Comment by xiaoxiao921** [comment]
I've read most of it and honestly, it's very good documentation. The only thing I'm not a fan of is that `nameof` is never used, like here for example

https://github.com/LethalCompanyCommunity/ModdingWiki/blob/fdad1985e1ced5068742de878a0542b81ac7fa9a/docs/dev/fundamentals/patching-code/monomod-examples.md?plain=1#L261-L267

Which would make updating in case of name changes a lot easier

**Review by Xilophor — COMMENTED** [review]
Looks really good to me, great work! I'll wait to approve until what iDeathHD (xiaoxiao921) mentioned is resolved.

**Review by Xilophor — APPROVED** [review]
lgtm

**Pull request merged**
